version: '2'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=app_development
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql
  rails:
    build: ./rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e development
    environment:
      - DOCKER_DATABASE_USERNAME=mysql
      - DOCKER_DATABASE_PASSWORD=password
    volumes:
      - ./rails:/app
    ports:
      - '3000:3000'
    depends_on:
      - db

