version: '2'
services:
  db:
    image: mysql:latest
  rails:
    build: ./rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails:/app
    ports:
      - '3000:3000'
    depends_on:
      - db

