# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 845098e0198b142b5768d5ed0fcae67b94ea8dc18c403d32eae7952f2ea995a6214e90820950afa3fe19a1174bc822493bbb9a684bcfe8fd061e5b4c2af5b78d

test:
  secret_key_base: 3ae8fbaa3d067dfd95b3b8824eaa27489ea49fbb159c9ff6581c9df0b559a1c5e212b6d68e96b97d04f717af33195eef82c52bc464c9988fd6d597b6b8ab63e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
